# 2.1 version of CircleCI, required for orbs.
# Cmp.: https://circleci.com/docs/2.0/configuration-reference/#orbs-requires-version-21
version: 2.1

# Orbs with basic actions, in particular to install node, aws stuff and the browser tools for testing
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  aws-ebcli: circleci/aws-elastic-beanstalk@2.0.1
  aws-s3cli: circleci/aws-s3@3.0.0
  browser-tools: circleci/browser-tools@1.2.2

# Jobs to run specific tasks, here just one large single "deploy" job
jobs:
  deploy:
    docker:
      # latest stable uses node 17 which causes problems with #OpenSSL
      - image: cimg/node:16.10
    steps:
      - node/install
      - checkout
      - browser-tools/install-chrome
      - aws-cli/setup:
          profile-name: udagram
      - aws-ebcli/setup
      - run:
          name: Backend-API install
          command: npm run backend:install
      - run:
          name: Frontend install
          command: npm run frontend:install
      - run:
          name: Backend-API testing
          command: npm run backend:test
      - run:
         name: Frontend testing
         command: npm run frontend:test
      - run:
          name: Backend-API build
          command: npm run backend:build
      - run:
          name: Frontend build
          command: npm run frontend:build
      - run:
          name: Backend-API deploy
          command: npm run backend:deploy
      - run:
          name: Frontend deploy
          command: npm run frontend:deploy

# Workflows to combine jobs - here just one :-)
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
